export enum FUNCTIONS {
    OVERVIEW = 'OVERVIEW',
    TIME_SERIES_DAILY = 'TIME_SERIES_DAILY',
    REAL_GDP = 'REAL_GDP',
    TOP_GAINERS_LOSERS = 'TOP_GAINERS_LOSERS',
    MARKET_STATUS = 'MARKET_STATUS',
    BALANCE_SHEET = 'BALANCE_SHEET',
    CASH_FLOW = 'CASH_FLOW',
}